name: 'Add a IP rule to a AWS Security Group'
description: 'Add a TCP Ingress rule to a AWS Security Group and cleans up after the workflow is done.'
inputs:
  aws-security-group-ids:
    description: 'comma separated list of AWS Security Group IDs'
    required: true
  port-range:
    description: 'Port range'
    required: false
    default: '443'
  description:
    description: 'The description of your IP rule'
    required: false
    default: 'GitHub Action'
runs:
  using: 'docker'
  image: 'Dockerfile' # 'docker://passeidireto/aws-add-ip-to-security-group-action'
  post-entrypoint: '/action_workspace/cleanup.sh'